README 添加目录  #16
NiX-Team/doc pull request #18
Opened 2018-05-10 14:44 UTC by GasenLi

2018-05-11 19:10 UTC, ganziqim requested changes

2018-05-11 19:10 UTC, ganziqim commented on README.md
> +
怎么多出来了个空行？

2018-05-11 19:10 UTC, ganziqim commented on README.md
> +* [钩子的安装和使用](#钩子的安装和使用)
是加文档的目录，不是下面那些内容的目录...

2018-05-13 13:54 UTC, GasenLi commented on README.md
> +
done

2018-05-13 13:55 UTC, merged